import type { Recipe } from "./types";

type Builtin = Omit<Recipe, "savedAt" | "origin" | "siteName"> & { accent: string; tags: string[] };

/**
 * House recipes bundled with the app. They work offline and show up on the
 * home page, in search, and as suggestions. Ids are prefixed with "d-".
 */
const RECIPES: Builtin[] = [
  {
    id: "d-garlic-butter-pasta",
    title: "Garlic Butter Pasta",
    image: "/recipes/garlic-butter-pasta.jpg",
    description: "Glossy, peppery and on the table in twenty minutes. The pantry dinner that never lets you down.",
    accent: "#d97757",
    yield: "2 servings",
    prepMinutes: 5,
    cookMinutes: 15,
    totalMinutes: 20,
    tags: ["quick", "pasta", "vegetarian", "dinner"],
    ingredients: [
      "200 g spaghetti or linguine",
      "4 tbsp unsalted butter",
      "5 cloves garlic, thinly sliced",
      "½ tsp red pepper flakes",
      "40 g parmesan, finely grated, plus more to serve",
      "Small handful parsley, chopped",
      "Zest of ½ lemon",
      "Salt and freshly ground black pepper",
    ],
    steps: [
      { text: "Bring a large pot of well-salted water to a boil. Add the pasta and cook 2 minutes less than the package says." },
      { text: "Meanwhile, melt the butter in a large skillet over medium-low heat. Add the garlic and pepper flakes and cook gently for 3 minutes, until the garlic is soft and just turning golden." },
      { text: "Scoop out a mugful of pasta water, then drain the pasta." },
      { text: "Add the pasta to the skillet with a big splash of pasta water. Toss over medium heat for 2 minutes until the sauce turns glossy and clings to the noodles." },
      { text: "Take the pan off the heat. Add the parmesan, parsley and lemon zest and toss again, loosening with more pasta water if needed." },
      { text: "Season with salt and lots of black pepper. Serve right away with extra parmesan." },
    ],
  },
  {
    id: "d-chickpea-curry",
    title: "Coconut Chickpea Curry",
    image: "/recipes/chickpea-curry.jpg",
    description: "Creamy, gently spiced and made almost entirely from cans. Great with rice or warm flatbread.",
    accent: "#c8a07f",
    yield: "4 servings",
    prepMinutes: 10,
    cookMinutes: 25,
    totalMinutes: 35,
    tags: ["vegan", "vegetarian", "curry", "dinner", "one pot"],
    ingredients: [
      "2 tbsp neutral oil",
      "1 onion, finely chopped",
      "3 cloves garlic, grated",
      "1 tbsp fresh ginger, grated",
      "2 tbsp curry powder",
      "1 tsp ground cumin",
      "1 can (400 g) chopped tomatoes",
      "1 can (400 ml) coconut milk",
      "2 cans (400 g each) chickpeas, drained",
      "2 large handfuls spinach",
      "Juice of 1 lime",
      "Salt, to taste",
      "Cilantro and cooked rice, to serve",
    ],
    steps: [
      { text: "Heat the oil in a large pot over medium heat. Add the onion with a pinch of salt and cook for 8 minutes, stirring now and then, until soft and golden." },
      { text: "Add the garlic, ginger, curry powder and cumin. Stir for 1 minute until fragrant." },
      { text: "Pour in the tomatoes and coconut milk, then add the chickpeas. Bring to a gentle simmer." },
      { text: "Simmer uncovered for 15 minutes, stirring occasionally, until thickened." },
      { text: "Stir in the spinach until wilted, then add the lime juice. Taste and season with salt." },
      { text: "Serve over rice, topped with cilantro." },
    ],
  },
  {
    id: "d-lemon-herb-chicken",
    title: "One-Pan Lemon Herb Chicken",
    image: "/recipes/lemon-herb-chicken.jpg",
    description: "Crisp-skinned thighs roasted over potatoes that soak up every drop of lemony pan juice.",
    accent: "#788c5d",
    yield: "4 servings",
    prepMinutes: 10,
    cookMinutes: 40,
    totalMinutes: 50,
    tags: ["chicken", "dinner", "one pan", "roast"],
    ingredients: [
      "8 bone-in, skin-on chicken thighs",
      "700 g baby potatoes, halved",
      "1 lemon, thinly sliced, plus juice of 1 lemon",
      "6 cloves garlic, smashed",
      "3 tbsp olive oil",
      "1 tbsp dried oregano",
      "4 sprigs fresh thyme",
      "1½ tsp salt",
      "½ tsp black pepper",
    ],
    steps: [
      { text: "Heat the oven to 220°C (425°F)." },
      { text: "On a large sheet pan, toss the potatoes, lemon slices and garlic with 2 tablespoons of the oil and half the salt." },
      { text: "Pat the chicken dry. Rub with the remaining oil, the oregano, the rest of the salt and the pepper. Nestle skin-side up on the potatoes and tuck in the thyme." },
      { text: "Roast for 40 minutes, until the skin is deep golden and the potatoes are tender." },
      { text: "Squeeze over the lemon juice and rest for 5 minutes before serving, spooning the pan juices over everything." },
    ],
  },
  {
    id: "d-fluffy-pancakes",
    title: "Fluffy Buttermilk Pancakes",
    image: "/recipes/fluffy-pancakes.jpg",
    description: "Tall, tender and lightly golden. The weekend stack.",
    accent: "#e0b469",
    yield: "10 pancakes",
    prepMinutes: 10,
    cookMinutes: 15,
    totalMinutes: 25,
    tags: ["breakfast", "vegetarian", "sweet"],
    ingredients: [
      "250 g all-purpose flour",
      "2 tbsp sugar",
      "2 tsp baking powder",
      "½ tsp baking soda",
      "½ tsp salt",
      "480 ml buttermilk",
      "2 eggs",
      "3 tbsp melted butter, plus more for the pan",
      "1 tsp vanilla extract",
      "Maple syrup, to serve",
    ],
    steps: [
      { text: "Whisk the flour, sugar, baking powder, baking soda and salt in a large bowl." },
      { text: "In another bowl, whisk the buttermilk, eggs, melted butter and vanilla." },
      { text: "Pour the wet ingredients into the dry and fold gently until just combined. A few lumps are fine. Let the batter rest for 5 minutes." },
      { text: "Heat a nonstick pan over medium heat and brush with butter." },
      { text: "Pour in about a third of a cup of batter per pancake. Cook for 2 minutes, until bubbles form and the edges look set." },
      { text: "Flip and cook for 1 minute more, until golden. Repeat with the rest of the batter and serve warm with maple syrup." },
    ],
  },
  {
    id: "d-tomato-soup",
    title: "Roasted Tomato Soup",
    image: "/recipes/tomato-soup.jpg",
    description: "Sweet, smoky roasted tomatoes blended silky smooth. Grilled cheese strongly encouraged.",
    accent: "#c4553a",
    yield: "4 servings",
    prepMinutes: 10,
    cookMinutes: 45,
    totalMinutes: 55,
    tags: ["soup", "vegetarian", "lunch", "comfort"],
    ingredients: [
      "1.2 kg ripe tomatoes, halved",
      "1 red onion, cut into wedges",
      "6 cloves garlic, unpeeled",
      "3 tbsp olive oil",
      "1 tsp salt",
      "750 ml vegetable stock",
      "1 tsp sugar",
      "Handful fresh basil",
      "60 ml heavy cream (optional)",
    ],
    steps: [
      { text: "Heat the oven to 200°C (400°F)." },
      { text: "Spread the tomatoes, onion and garlic on a sheet pan. Toss with the oil and salt." },
      { text: "Roast for 35 minutes, until the tomatoes are collapsed and charred at the edges." },
      { text: "Squeeze the garlic out of its skins into a pot. Add the roasted vegetables, stock and sugar and simmer for 10 minutes." },
      { text: "Add the basil and blend until smooth. Stir in the cream if using, then taste and adjust the seasoning." },
    ],
  },
  {
    id: "d-soft-scrambled-eggs",
    title: "Soft Scrambled Eggs",
    image: "/recipes/soft-scrambled-eggs.jpg",
    description: "Low heat, constant stirring and patience give you creamy, custardy curds.",
    accent: "#e8c547",
    yield: "1 serving",
    prepMinutes: 2,
    cookMinutes: 6,
    totalMinutes: 8,
    tags: ["breakfast", "quick", "vegetarian", "eggs"],
    ingredients: [
      "3 eggs",
      "1 tbsp butter",
      "1 tbsp crème fraîche or cream",
      "Pinch of salt",
      "Chives, finely chopped",
      "Toast, to serve",
    ],
    steps: [
      { text: "Crack the eggs into a bowl with the salt and beat until completely smooth." },
      { text: "Melt the butter in a small nonstick pan over low heat. Add the eggs." },
      { text: "Stir constantly with a spatula, scraping the bottom and sides, for 5 minutes, until small soft curds form and the eggs look like loose custard." },
      { text: "Take the pan off the heat while the eggs still look slightly underdone. Stir in the crème fraîche." },
      { text: "Pile onto toast and finish with chives." },
    ],
  },
  {
    id: "d-egg-fried-rice",
    title: "Egg Fried Rice",
    image: "/recipes/egg-fried-rice.jpg",
    description: "The best use for yesterday's rice. Fast, smoky and endlessly adaptable.",
    accent: "#a87b4f",
    yield: "2 servings",
    prepMinutes: 5,
    cookMinutes: 10,
    totalMinutes: 15,
    tags: ["quick", "rice", "dinner", "vegetarian"],
    ingredients: [
      "500 g cooked rice, cold (day-old is best)",
      "3 eggs, beaten",
      "2 tbsp neutral oil",
      "3 spring onions, sliced, whites and greens separated",
      "2 cloves garlic, minced",
      "150 g frozen peas",
      "2 tbsp soy sauce",
      "1 tsp toasted sesame oil",
      "White pepper, to taste",
    ],
    steps: [
      { text: "Break up any clumps in the rice with your hands." },
      { text: "Heat 1 tablespoon of the oil in a wok over high heat. Add the eggs and scramble for 1 minute until just set, then tip onto a plate." },
      { text: "Add the remaining oil, the spring onion whites and the garlic. Stir-fry for 30 seconds." },
      { text: "Add the rice and peas. Stir-fry for 4 minutes, pressing the rice against the hot wok, until heated through and slightly crisp." },
      { text: "Add the soy sauce, sesame oil and the eggs back in. Toss for 1 minute, breaking up the egg." },
      { text: "Season with white pepper and serve topped with the spring onion greens." },
    ],
  },
  {
    id: "d-smashed-potatoes",
    title: "Crispy Smashed Potatoes",
    image: "/recipes/smashed-potatoes.jpg",
    description: "Creamy inside, shatteringly crisp outside. Boil, smash, roast.",
    accent: "#8a9a5b",
    yield: "4 servings",
    prepMinutes: 5,
    cookMinutes: 50,
    totalMinutes: 55,
    tags: ["side", "vegetarian", "vegan", "potatoes"],
    ingredients: [
      "1 kg small waxy potatoes",
      "4 tbsp olive oil",
      "1½ tsp flaky salt",
      "½ tsp black pepper",
      "1 tsp garlic powder",
      "2 tbsp chopped rosemary or parsley",
    ],
    steps: [
      { text: "Heat the oven to 230°C (450°F). Put the potatoes in a pot, cover with salted cold water and bring to a boil." },
      { text: "Simmer for 20 minutes, until a knife slides in easily. Drain and let them steam dry for 5 minutes." },
      { text: "Spread the potatoes on an oiled sheet pan. Press each one flat with the bottom of a glass until about 1 cm thick." },
      { text: "Drizzle with the remaining oil and season with salt, pepper and garlic powder." },
      { text: "Roast for 25 minutes, until deeply golden and crisp at the edges. Scatter with herbs and serve." },
    ],
  },
  {
    id: "d-chocolate-chip-cookies",
    title: "Brown Butter Chocolate Chip Cookies",
    image: "/recipes/chocolate-chip-cookies.jpg",
    description: "Nutty brown butter, crisp edges and puddles of chocolate.",
    accent: "#7a4a2e",
    yield: "18 cookies",
    prepMinutes: 20,
    cookMinutes: 12,
    totalMinutes: 32,
    tags: ["baking", "dessert", "sweet", "vegetarian"],
    ingredients: [
      "170 g unsalted butter",
      "200 g light brown sugar",
      "50 g granulated sugar",
      "1 egg plus 1 egg yolk",
      "2 tsp vanilla extract",
      "250 g all-purpose flour",
      "¾ tsp baking soda",
      "1 tsp salt",
      "200 g dark chocolate, chopped",
      "Flaky salt, for topping",
    ],
    steps: [
      { text: "Melt the butter in a light-colored pan over medium heat, swirling, for 5 minutes, until it smells nutty and the solids turn golden brown. Pour into a large bowl and cool for 10 minutes." },
      { text: "Heat the oven to 180°C (350°F) and line two baking sheets with parchment." },
      { text: "Whisk both sugars into the butter, then whisk in the egg, yolk and vanilla until glossy." },
      { text: "Stir in the flour, baking soda and salt until just combined, then fold in the chocolate." },
      { text: "Scoop into balls about 3 tablespoons each and space them well apart on the sheets." },
      { text: "Bake for 11 minutes, until golden at the edges but still soft in the middle. Sprinkle with flaky salt and cool on the sheet for 5 minutes." },
    ],
  },
  {
    id: "d-shrimp-tacos",
    title: "Garlic Lime Shrimp Tacos",
    image: "/recipes/shrimp-tacos.jpg",
    description: "Juicy charred shrimp, crunchy slaw and a quick chipotle crema.",
    accent: "#3f7d7a",
    yield: "4 servings",
    prepMinutes: 15,
    cookMinutes: 5,
    totalMinutes: 20,
    tags: ["quick", "seafood", "tacos", "dinner"],
    ingredients: [
      "500 g large shrimp, peeled and deveined",
      "2 cloves garlic, minced",
      "1 tsp chili powder",
      "½ tsp ground cumin",
      "2 tbsp olive oil",
      "2 limes",
      "120 g sour cream",
      "1 chipotle in adobo, finely chopped",
      "2 cups shredded cabbage",
      "8 small corn tortillas",
      "Cilantro and salt, to taste",
    ],
    steps: [
      { text: "Toss the shrimp with the garlic, chili powder, cumin, 1 tablespoon of oil, the juice of half a lime and a big pinch of salt." },
      { text: "Stir together the sour cream, chipotle and a squeeze of lime. Toss the cabbage with the juice of the other half lime and a pinch of salt." },
      { text: "Warm the tortillas in a dry skillet over high heat for 30 seconds per side. Wrap in a towel to keep warm." },
      { text: "Add the remaining oil to the skillet. Cook the shrimp in a single layer for 2 minutes per side, until pink and charred." },
      { text: "Fill each tortilla with slaw and shrimp, drizzle with chipotle crema and top with cilantro. Serve with lime wedges." },
    ],
  },
];

export const DEFAULT_RECIPES: Recipe[] = RECIPES.map((r) => ({
  ...r,
  origin: "builtin",
  siteName: "Lemme Cook Kitchen",
  savedAt: 0,
}));

export function getDefaultRecipe(id: string) {
  return DEFAULT_RECIPES.find((r) => r.id === id);
}

export const CATEGORIES = [
  { label: "Quick", query: "quick" },
  { label: "Vegetarian", query: "vegetarian" },
  { label: "Pasta", query: "pasta" },
  { label: "Chicken", query: "chicken" },
  { label: "Breakfast", query: "breakfast" },
  { label: "Seafood", query: "seafood" },
  { label: "Dessert", query: "dessert" },
  { label: "Soup", query: "soup" },
];

/** Simple local match over title, tags and ingredients. */
export function searchDefaults(query: string): Recipe[] {
  const words = query.toLowerCase().split(/\s+/).filter(Boolean);
  if (!words.length) return [];
  return DEFAULT_RECIPES.filter((r) => {
    const hay = [r.title, ...(r.tags ?? []), ...r.ingredients].join(" ").toLowerCase();
    return words.every((w) => hay.includes(w.replace(/s$/, "")));
  });
}

/** A few house recipes to suggest, skipping the one you're on. */
export function suggestDefaults(excludeId?: string, count = 3): Recipe[] {
  return DEFAULT_RECIPES.filter((r) => r.id !== excludeId).slice(0, count);
}
